// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbo

type Datum struct {
	ID           string
	Type         string
	Filename     string
	Filepath     string
	Burn         string
	Expire       string
	PasswordHash string
	PasswordSalt string
	EncryptSalt  string
}
